# https://docs.microsoft.com/azure/devops/pipelines/languages/android
parameters:
  name: 'android_e2e_tests'
  vmImage: 'macOS-10.15'
  MOCHA_FILE: 'mocha-test-results.xml'
  CHROMEDRIVER_VERSION: 2.44
  NODE_VERSION: 14.x
  ANDROID_SDK_VERSION: 28

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
      TERM: dumb
      MOCHA_FILE: ${{ parameters.MOCHA_FILE }}
      ANDROID_SDK_VERSION: ${{ parameters.ANDROID_SDK_VERSION }}
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: ${{ parameters.NODE_VERSION }}
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - script: npm install --chromedriver_version="${{ parameters.CHROMEDRIVER_VERSION }}"
      displayName: Install Node dependencies
    - script: npm test
      displayName: NPM Test
    - script: npm install -g mjpeg-consumer
      displayName: Install MJPEG Consumer
    - script: bash ci-jobs/scripts/start-emulator.sh
      displayName: Create and run Emulator
    - script: |
        pushd "$(pwd)/espresso-server"
        ./gradlew -PappiumTargetPackage=io.appium.android.apis app:assembleAndroidTest
        popd
      displayName: Prebuild the server
    - script: npx mocha --timeout 300000 --reporter mocha-multi-reporters --reporter-options config-file=./ci-jobs/mocha-config.json --recursive build/test/functional/driver-e2e-specs.js -g @skip-ci -i --exit
      displayName: Run tests
    # temporary for now
    - script: npx mocha --timeout 300000 --reporter mocha-multi-reporters --reporter-options config-file=./ci-jobs/mocha-config.json --recursive build/test/functional/jetpack-compose-attributes-e2e-specs.js -g @skip-ci -i --exit
      displayName: Run tests
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testResultsFiles: ${{ parameters.MOCHA_FILE }}
