# https://docs.microsoft.com/azure/devops/pipelines/languages/android
parameters:
  name: 'android_e2e_tests'
  vmImage: 'macOS-10.15'
  MOCHA_FILE: 'mocha-test-results.xml'
  CHROMEDRIVER_VERSION: 2.44
  NODE_VERSION: 10.x
  ANDROID_SDK_VERSION: 28

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
      TERM: dumb
      MOCHA_FILE: ${{ parameters.MOCHA_FILE }}
      ANDROID_SDK_VERSION: ${{ parameters.ANDROID_SDK_VERSION }}
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: ${{ parameters.NODE_VERSION }}
    - script: npm install --chromedriver_version="${{ parameters.CHROMEDRIVER_VERSION }}"
      displayName: Install Node dependencies
    - script: npm test
      displayName: NPM Test
    - script: npm install -g mjpeg-consumer
      displayName: Install MJPEG Consumer
    - script: bash ci-jobs/scripts/start-emulator.sh
      displayName: Create and run Emulator
    - script: npm run build
      displayName: Build
    - script: npx mocha --timeout 6000000 --reporter mocha-multi-reporters --reporter-options config-file=./ci-jobs/mocha-config.json --recursive build/test/functional/ -g @skip-ci -i --exit
      env:
        JAVA_HOME: $(JAVA_HOME_11_X64)
        PATH: $(JAVA_HOME_11_X64)/bin:$(PATH)
      displayName: Run tests
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testResultsFiles: ${{ parameters.MOCHA_FILE }}
