# https://docs.microsoft.com/azure/devops/pipelines/languages/android
parameters:
  name: 'android_e2e_tests'
  vmImage: 'macOS-12'
  CHROMEDRIVER_VERSION: 2.44
  NODE_VERSION: 16.x
  ANDROID_SDK_VERSION: 28

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
      TERM: dumb
      ANDROID_SDK_VERSION: ${{ parameters.ANDROID_SDK_VERSION }}
      APPIUM_TEST_SERVER_PORT: 4567
      APPIUM_TEST_SERVER_HOST: '127.0.0.1'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: ${{ parameters.NODE_VERSION }}
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - script: |
        npm install -g appium@next
        npm install --chromedriver_version="${{ parameters.CHROMEDRIVER_VERSION }}"
      displayName: Install Node dependencies
    - script: npm install -g mjpeg-consumer
      displayName: Install MJPEG Consumer
    - script: bash ci-jobs/scripts/start-emulator.sh
      displayName: Create and run Emulator
    - script: |
        pushd "$(pwd)/espresso-server"
        ./gradlew -PappiumTargetPackage=io.appium.android.apis app:assembleAndroidTest
        popd
      displayName: Prebuild the server
    - script: |
        bash ci-jobs/scripts/run_server.sh
        npx mocha --timeout 300000 \
          ./test/functional/driver-e2e-specs.js \
          ./test/functional/commands/jetpack-compose-attributes-e2e-specs.js \
          -g @skip-ci -i --exit
      displayName: Run tests

