jobs:
  - job: EspressoCI
    pool:
      vmImage: macOS-10.15
    variables:
      CI: true
      TERM: dumb
      ANDROID_AVD: test
      ANDROID_SDK_VERSION: 28
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 10.x
    - script: npm install
      displayName: Install Node dependencies
    - script: npm test
      displayName: NPM Test
    - script: npm run build
      displayName: Build
    - script: npm test
      displayName: Run Unit Tests
