jobs:
  - job: EspressoCI
    pool:
      vmImage: macOS-12
    variables:
      CI: true
      TERM: dumb
      ANDROID_AVD: test
      ANDROID_SDK_VERSION: 28
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 16.x
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - script: |
        npm install -g appium@next
        npm install
      displayName: Install Node dependencies
    - script: npm run lint
      displayName: Lint
    - script: npm run test
      displayName: NPM Test
