jobs:
  - job: EspressoCI
    pool:
      vmImage: macOS-10.14
    variables:
      CI: true
      TERM: dumb
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 10.x
    - script: npm install
      displayName: Install Node dependencies
    - script: npm test
      displayName: NPM Test
    - script: npm run build
      displayName: Build
    - script: npm test
      displayName: Run Node Unit Tests
    - task: Gradle@2
      inputs:
        workingDirectory: espresso-server
        gradleWrapperFile: espresso-server/gradlew
        gradleOptions: '-Xmx3072m'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: test
