jobs:
  - job: EspressoCI
    pool:
      vmImage: macOS-10.15
    variables:
      CI: true
      TERM: dumb
      ANDROID_AVD: test
      ANDROID_SDK_VERSION: 28
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 14.x
    - script: npm install
      displayName: Install Node dependencies
      env:
        JAVA_HOME: $(JAVA_HOME_11_X64)
        PATH: $(JAVA_HOME_11_X64)/bin:$(PATH)
    - script: npm test
      displayName: NPM Test
