jobs:
  - job: EspressoCI
    pool:
      vmImage: macOS-10.15
    variables:
      CI: true
      TERM: dumb
      ANDROID_AVD: test
      ANDROID_SDK_VERSION: 28
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 14.x
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - script: npm install
      displayName: Install Node dependencies
    - script: npm test
      displayName: NPM Test
