# https://docs.microsoft.com/azure/devops/pipelines/languages/android
jobs:
  - job: gradle_junit_tests
    steps:
      - task: Gradle@2
        inputs:
          workingDirectory: espresso-server
          gradleWrapperFile: espresso-server/gradlew
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: test
  - template: templates/android-e2e-template.yml
    parameters:
      name: sdk28_e2e_tests
      CHROMEDRIVER_VERSION: 2.40
      ANDROID_SDK_VERSION: 28
  - template: templates/android-e2e-template.yml
    parameters:
      name: sdk25_e2e_tests
      CHROMEDRIVER_VERSION: 2.22
      ANDROID_SDK_VERSION: 25
  - template: templates/android-e2e-template.yml
    parameters:
      name: sdk23_e2e_tests
      CHROMEDRIVER_VERSION: 2.20
      ANDROID_SDK_VERSION: 23