# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pool:
  vmImage: macOS-12

variables:
  CI: true


jobs:
  - job: npm_unit_tests
    variables:
      TERM: dumb
      ANDROID_AVD: test
      ANDROID_SDK_VERSION: 28
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 16.x
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - script: npm install
      displayName: Install Node dependencies
    - script: npm run lint
      displayName: Lint
    - script: npm run test
      displayName: NPM Test
  - job: gradle_junit_tests
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Gradle@2
      inputs:
        workingDirectory: espresso-server
        gradleWrapperFile: espresso-server/gradlew
        gradleOptions: '-Xmx3072m'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: test
  - template: templates/android-e2e-template.yml
    parameters:
      name: sdk30_e2e_tests
      CHROMEDRIVER_VERSION: 83.0.4103.39
      ANDROID_SDK_VERSION: 30
  - template: templates/android-e2e-template.yml
    parameters:
      name: sdk29_e2e_tests
      CHROMEDRIVER_VERSION: 74.0.3729.6
      ANDROID_SDK_VERSION: 29
  - template: templates/android-e2e-template.yml
    parameters:
      name: sdk25_e2e_tests
      CHROMEDRIVER_VERSION: 2.24
      ANDROID_SDK_VERSION: 25
  - template: templates/android-e2e-template.yml
    parameters:
      name: sdk23_e2e_tests
      CHROMEDRIVER_VERSION: 2.20
      ANDROID_SDK_VERSION: 23
