name: Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - run: npm install
      name: Install dependencies
    - run: npm test
      name: Run NPM Test
    - run: |
        rm -rf package-lock.json
        npm prune --production
        rm -rf node_modules/appium
      name: Remove dev dependencies and appium peer dependencies
    - run: npm shrinkwrap
      name: Create shrinkwrap
    - run: npm install --only=dev
      name: Install dev decepdencies for the release
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      name: Release

